--- 
pipeline: 
  build: 
    image: node:slim
    commands: 
      - "npm install"
  publish: 
    image: plugins/docker:1.12
    username: shivahs
    email: shivaprasad1993@gmail.com
    password: Guitarist@2012
    repo: ridecircle/test
    tags: 
      - latest
    dockerfile: ./Dockerfile
