pipeline:
  build:
    image: node:lite
    commands:
      - npm install
    
  publish:
    image: plugins/docker
    username: shivahs
    password: Guitarist@2012
    repo: ridecircle/test
    tags: [ 1.0.0, 1.0, latest ]
 
  when:
    event:push
