--- 
pipeline: 
  build: 
    image: node:slim
    commands: 
      - "npm install"
  publish: 
    image: plugins/docker
    password: Guitarist@2012
    repo: ridecircle/test
    tags: 
      - "1.0.0"
      - 1.0
      - latest
    username: shivahs
  when: 
    event: push
